name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do Código
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Você está usando bibliotecas modernas — melhor usar 18+

      - name: 📦 Instalar Dependências
        run: npm install

      - name: ✅ Rodar Testes com Jest
        run: npm test

      - name: 📤 Upload de Resultados (se os testes falharem)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: coverage/
